#### Finding Data Analyst Jobs in Gurugram, Harayana, India.  
##### These filter are already applied on the website.

In [1]:
# Import the necessary libraries
from bs4 import BeautifulSoup  # For parsing HTML
import requests  # For making HTTP requests
import pandas as pd  # For data manipulation and analysis

In [2]:
# Define the URL of the website to scrape
website = "https://www.linkedin.com/jobs/search?keywords=Data%20Analyst&location=Gurugram%2C%20Haryana%2C%20India&geoId=115884833&trk=public_jobs_jobs-search-bar_search-submit&position=1&pageNum=0"

# Send an HTTP request to the URL and get the response
result = requests.get(website)
content = result.text

# Parse the HTML content of the webpage using BeautifulSoup
# 'lxml' is one of the parsers supported by BeautifulSoup
soup = BeautifulSoup(content, 'lxml')

In [3]:
# print(soup.prettify())

In [4]:
# Find the <ul> element with the class 'jobs-search__results-list' in the parsed HTML content
box = soup.find('ul', class_ = 'jobs-search__results-list')

In [5]:
# Initializing an empty list to store the data extracted
df_data = []

# Loop through each <li> element within the <ul> element
for data in box.find_all('li'):
    
    # Extract the job title from the <h3> element with the class 'base-search-card__title'
    title = data.find('h3', class_='base-search-card__title').get_text().strip()
    
    # Extract the subtitle (if available) from the <a> element with the class 'hidden-nested-link'
    subtitle_element = data.find('a', class_='hidden-nested-link')
    if subtitle_element:
        subtitle = subtitle_element.get_text().strip()
    else:
        subtitle = 'Subtitle not found'
    
    # Extract the city/location from the <span> element with the class 'job-search-card__location'
    city = data.find('span', class_='job-search-card__location').get_text().strip()
    
    # Extract the posting time from the <time> element with the class 'job-search-card__listdate'
    time_element = data.find('time', class_='job-search-card__listdate')
    if time_element:
        time = time_element.get_text().strip()
    else:
        time = 'Time not found'
        
    # Append the extracted data to the list
    df_data.append([title, subtitle, city, time])
        
# Create a DataFrame from the collected data with appropriate column names
df = pd.DataFrame(df_data, columns=['title', 'subtitle', 'city', 'time'])

In [6]:
# Save the DataFrame to a CSV file named 'data_gurugram'
# Set index=False to avoid writing row indices to the CSV file
df.to_csv('data_gurugram', index=False)

In [7]:
# Print the df
df

,title,subtitle,city,time
0,Data Analyst,EXL,"Gurugram, Haryana, India",1 week ago
1,Data Analyst,Concentrix,"Gurugram, Haryana, India",3 weeks ago
2,Data Analyst,Ticketmaster,"Gurugram, Haryana, India",1 week ago
3,Analyst- Data science,American Express,"Gurugram, Haryana, India",2 days ago
4,Logistics Data Analyst,Circle K,"Gurugram, Haryana, India",1 week ago
5,Data Analytics & Strategy,Airtel Payments Bank,"Gurugram, Haryana, India",4 weeks ago
6,Data Analyst / Senior Data Analyst,Urban Company,"Gurugram, Haryana, India",1 week ago
7,Data Engineer,Nykaa,"Gurugram, Haryana, India",3 weeks ago
8,Business Intelligence Analyst,Concentrix,"Gurugram, Haryana, India",3 weeks ago
9,Analyst - Data Science,United Airlines,"Gurugram, Haryana, India",2 weeks ago
10,Data Analysis & Interpretation,PURVIEW,"Gurugram, Haryana, India",1 week ago
11,Specialist – Data Analytics & Insight - Victor...,Marsh McLennan,"Gurugram, Haryana, India",3 weeks ago
12,Data Analyst,Acme Services,"Gurugram, Haryana, India",1 week ago
13,Analyst/Senior Analyst – Data Analytics,D. E. Shaw India Private Limited,"Gurugram, Haryana, India",2 weeks ago
14,Analyst/Senior Analyst – Data Analytics,D. E. Shaw India Private Limited,"Gurugram, Haryana, India",6 days ago
15,Senior Data Analyst,TELUS International,"Gurugram, Haryana, India",2 weeks ago
16,"Data Delivery Analyst (Python,SQL) - Periscope",McKinsey & Company,"Gurugram, Haryana, India",2 weeks ago
17,Data Analyst-Gurugram,Talent Socio(We're Hiring!!),"Gurugram, Haryana, India",1 month ago
18,Power BI Expert,EXL,"Gurugram, Haryana, India",1 month ago
19,Data Analyst,Targray,"Gurugram, Haryana, India",1 month ago
20,Business Analyst - Data Analyst-ANA008478,Genpact,"Gurugram, Haryana, India",2 weeks ago
21,Data Engineer-Gurgaon/Pune/Bangalore/Noida-Imm...,EXL,"Gurugram, Haryana, India",3 weeks ago
22,Big Data Analyst,AI Staffing Ninja,"Gurugram, Haryana, India",3 weeks ago
23,Data Quality Analyst,Xebia,"Gurugram, Haryana, India",4 weeks ago
24,Analyst-Data Analytics [SQL/Python],myGwork - LGBTQ+ Business Community,"Gurugram, Haryana, India",1 day ago
25,BI Analyst - Team Lead,EPAM Systems,"Gurugram, Haryana, India",6 days ago
26,Lead Data Engineer / Principal Data Engineer,MakeMyTrip,"Gurugram, Haryana, India",Time not found
27,Senior Data Analyst,Home Credit India,"Gurugram, Haryana, India",4 days ago
28,Assistant Manager–Data Analyst-ANA010462,Genpact,"Gurugram, Haryana, India",1 week ago
29,Assistant Manager–Data Analyst-ANA010452,Genpact,"Gurugram, Haryana, India",1 week ago
30,Senior Data Analyst,Zypp Electric,"Gurugram, Haryana, India",4 weeks ago
31,Assistant Manager–Data Analyst-ANA010468,Genpact,"Gurugram, Haryana, India",1 week ago
32,Assistant Manager : Data Analyst-ANA010443,Genpact,"Gurugram, Haryana, India",2 weeks ago
33,Assistant Manager–Data Analyst-ANA010448,Genpact,"Gurugram, Haryana, India",1 week ago
34,"Consulting Analyst, Growth Analytics - Gurugra...",Frost & Sullivan,"Gurugram, Haryana, India",3 weeks ago
35,Data Dashboard,Kezan Consulting- A Unit of Kezan India Privat...,"Gurugram, Haryana, India",2 months ago
36,Interesting Job Opportunity: Data Analyst - SQ...,Techno-Comp Computer Services Pvt. Ltd.,"Gurugram, Haryana, India",2 days ago
37,Data Engineer,EXL,"Gurugram, Haryana, India",2 weeks ago
38,Data Engineer,EXL,"Gurugram, Haryana, India",2 weeks ago
39,Assistant Manager–Data Analyst-ANA010475,Genpact,"Gurugram, Haryana, India",1 week ago
40,Data Modeler,Coforge,"Gurugram, Haryana, India",1 day ago
41,Senior Data Engineer I / Senior Data Engineer II,MakeMyTrip,"Gurugram, Haryana, India",Time not found
42,Data Analyst,Subtitle not found,"Gurugram, Haryana, India",7 months ago
43,"Analyst, Data & Analytics",Stryker,"Gurugram, Haryana, India",1 week ago
44,Sr. BI Analyst,EPAM Systems,"Gurugram, Haryana, India",6 days ago
45,Asst Dir-Data Analyst,Moody's Corporation,"Gurugram, Haryana, India",2 weeks ago
46,Consultant - Data Analytics-CPG047857,Genpact,"Gurugram, Haryana, India",2 weeks ago
47,Business System Analyst,Sun Life,"Gurugram, Haryana, India",Time not found
48,Analyst - Business Intelligence,United Airlines,"Gurugram, Haryana, India",2 weeks ago
49,Data Engineer,RSA India (An Intact Company),"Gurugram, Haryana, India",3 weeks ago
50,Data Analyst,Alp Consulting Ltd.,"Gurugram, Haryana, India",1 week ago
51,BI Manager (Power BI) - Immediate joiners only,Concentrix,"Gurugram, Haryana, India",2 weeks ago
52,Lead BI Analyst,EPAM Systems,"Gurugram, Haryana, India",2 weeks ago
53,SQL Developer,TekFocus Minds,"Gurugram, Haryana, India",2 weeks ago
54,Data Engineer_3+ years_ immediate hiring_ Loca...,EXL,"Gurugram, Haryana, India",3 weeks ago
55,Manager - Data Analytics-COR027694,Genpact,"Gurugram, Haryana, India",2 weeks ago
56,Data Engineer,Battery Smart,"Gurugram, Haryana, India",3 weeks ago
57,Senior Analyst - Competitive intelligence Pharma,Course5i,"Gurugram, Haryana, India",3 weeks ago
58,Data Engineer,ClearPier Inc,"Gurugram, Haryana, India",5 days ago
59,Perf. Media Analytics - Sr Analyst - Analytics,dentsu,"Gurugram, Haryana, India",4 days ago